// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsyhwfujpzwsycdiirpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeWh3ZnVqcHp3c3ljZGlpcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjQ3OTAsImV4cCI6MjA2MzYwMDc5MH0.IxGMjm6wRanTpSsxlFTLIm3nerj2lbmzBqICp3GqzJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);